Data wrangling 1

1. Import all the required Python Libraries

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
%matplotlib inline

In [ ]:
from sklearn import metrics

In [ ]:
from sklearn import metrics

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
from sklearn.model_selection import train_test_split

2. Locate an open source data from the web

....

3. Load the Dataset into Pandas DataFrame.

In [ ]:
df= pd.read_csv("https://raw.githubusercontent.com/okfn/dataportals.org/master/data/portals.csv")

In [ ]:
print(df)

                         name  \
0                   a2gov_org
1    acikveri-sahinbey-bel-tr
2            africa_open_data
3     ajuntament-de-tarragona
4       ajuntament-de-terassa
..                        ...
599           open-data-nepal
600                   stat-tj
601                dadosjusbr
602       bratislava-opendata
603        sk-kosice-opendata

                                                 title  \
0                                  Ann Arbor, Michigan
1                      Açık Veri Portali - Test Yayını
2                                     Africa Open Data
3                                  Open Data Tarragona
4                                    Open Data Terassa
..                                                 ...
599                                    Open Data Nepal
600  Agency on Statistics under President of the Re...
601                                         DadosJusBR
602                        Bratislava Open Data Portal
603                The city of Košice Open Data Portal

                                                   url  \
0    http://www.a2gov.org/services/data/Pages/defau...
1              http://acikveri.sahinbey.bel.tr/dataset
2                           http://africaopendata.org/
3                       http://opendata.tarragona.cat/
4                        http://opendata.terrassa.cat/
..                                                 ...
599                         https://opendatanepal.com/
600                             https://www.stat.tj/en
601                            https://dadosjusbr.org/
602                     https://opendata.bratislava.sk
603                         https://opendata.kosice.sk

                                                author  \
0                                    City of Ann Arbor
1                                             pinardag
2                                     Africa Open Data
3                              Ajuntament de Tarragona
4                                Ajuntament de Terassa
..                                                 ...
599                               Open Knowledge Nepal
600  The Statistical Agency under President of the ...
601  Instituto Federal de Alagoas (IFAL) in partner...
602  Magistrát hlavného mesta Slovenskej republiky ...
603                             Magistrát mesta Košice

                                             publisher      issued  \
0                                    City of Ann Arbor         NaN
1                                  SahinBey Belediyesi  31/01/2015
2                                     Africa Open Data         NaN
3                              Ajuntament de Tarragona         NaN
4                                Ajuntament de Terassa         NaN
..                                                 ...         ...
599                               Open Knowledge Nepal  2018-03-03
600  The Statistical Agency under President of the ...         NaN
601                       Instituto Federal de Alagoas  2018-12-31
602                             The city of Bratislava         NaN
603                                 The city of Košice         NaN

    publisher_classification  \
0                        NaN
1                 Government
2                        NaN
3                 Government
4                 Government
..                       ...
599                Community
600               Government
601                Community
602               Government
603               Government

                                           description                   tags  \
0          City of Ann Arbor's Open Data Catalog (USA)      ctic unitedstates
1        The first official open data portal of Turkey        turkey national
2    Africa's largest central repository for Govern...            ckan africa
3                                  Open Data Tarragona             city spain
4                                    Open Data Terassa             city spain
..                                                 ...                    ...
599  A civil society initiative to make Nepal’s dat...             ckan nepal
600  The information in the Statistical Agency is p...  tajikistan statistics
601  The portal consumes or scrapes data from sever...       brazil judiciary
602  Open data is information or data that is freel...    bratislava slovakia
603  The Open Data Portal is one of the outputs of ...        kosice slovakia

           license_id  ...                 place                location  \
0                 NaN  ...   Ann Arbor, Michigan  42.2681569,-83.7312291
1             Unknown  ...      Gaziantep,Turkey    37.0587715,37.380137
2                 NaN  ...                Africa    2.0000003,15.9999997
3                 NaN  ...             Tarragona         41.1157, 1.2496
4                 NaN  ...               Terrasa         41.5611, 2.0081
..                ...  ...                   ...                     ...
599             cc-by  ...      Kathmandu, Nepal         27.7097,85.3209
600  Other (Not Open)  ...            Tajikistan   38.5754817,68.7900625
601             cc-by  ...                Brazil     15.74706, -47.89593
602               NaN  ...  Bratislava, Slovakia      48.14409, 17.10971
603               NaN  ...      Košice, Slovakia      48.71442, 21.23508

    country  language  status           metadatacreated  \
0        US        en  active  2011-06-27T18:12:57.439Z
1        TR        tr  active                       NaN
2        AF        en  active  2013-03-15T07:17:26.251Z
3        ES  ca es en  active                       NaN
4        ES     es en  active                       NaN
..      ...       ...     ...                       ...
599      NP        en  active         2022-07-01T08:37Z
600      TJ        en  active       2022-07-17T16:49:49
601      BR        pt  active      2022-07-24T22:38:06Z
602      SK        sk  active      2023-05-04T14:22:56Z
603      SK        sk  active      2023-05-05T16:15:56Z

                          generator                        api_endpoint  \
0                               NaN                                 NaN
1                               NaN                                 NaN
2                       CKAN: 2.1.3      http://africaopendata.org/api/
3                               NaN                                 NaN
4                               NaN                                 NaN
..                              ...                                 ...
599                            ckan       https://opendatanepal.com/api
600                             NaN                                 NaN
601  Custom/in-house implementation         https://api.dadosjusbr.org/
602  Custom/in-house implementation  https://opendata.bratislava.sk/api
603                      ArcGIS Hub                                 NaN

                           api_type  \
0                               NaN
1                               NaN
2                               NaN
3                               NaN
4                               NaN
..                              ...
599                        CKAN API
600                             NaN
601  Custom/in-house implementation
602  Custom/in-house implementation
603                             NaN

                                full_metadata_download
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
599                                                NaN
600                                                NaN
601                                                NaN
602                                                NaN
603  https://open-data-kosice-mesto.hub.arcgis.com/...

[604 rows x 22 columns]

now there is a data processing method

In [ ]:
df.isnull()

,name,title,url,author,publisher,issued,publisher_classification,description,tags,license_id,...,place,location,country,language,status,metadatacreated,generator,api_endpoint,api_type,full_metadata_download
0,False,False,False,False,False,True,True,False,False,True,...,False,False,False,False,False,False,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,True
2,False,False,False,False,False,True,True,False,False,True,...,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,True,True,True,True,True
4,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
600,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
601,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
602,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
603,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,False,False,True,True,False

describe() : returns the statistical summary of dataframe or series.

size() : count the number of element along given axis.

shape() : gives the number of elements in each dimension of an array.

ndim() : return the number of dimensions of an array.

In [ ]:
df.describe()

,name,title,url,author,publisher,issued,publisher_classification,description,tags,license_id,...,place,location,country,language,status,metadatacreated,generator,api_endpoint,api_type,full_metadata_download
count,604,604,604,539,543,98,222,555,531,289,...,602,581,589,595,604,462,97,46,79,17
unique,600,598,600,497,506,88,7,551,278,43,...,496,494,129,77,3,426,25,46,9,17
top,state_of_washington,Washington,http://dados.recife.pe.gov.br,African Development Bank Group,African Development Bank Group,27/08/2015,Government,Open Data portal for the European Commission a...,canada,cc-by,...,Italy,"0,0",US,en,active,2018-09-12T10:58:52Z,CKAN,http://africaopendata.org/api/,CKAN API,https://data.qld.gov.au/api/3/action/current_p...
freq,4,4,2,21,22,2,193,2,45,48,...,9,10,100,271,587,30,37,1,38,1

In [ ]:
size = df.size
shape = df.shape
df_ndim = df.ndim
series_ndim = df["name"].ndim
print("Size - {}\nShape = {}\nShape[0]x shape[1]= {}".format(size,shape, shape[0]* shape[1]))

Size - 13288
Shape = (604, 22)
Shape[0]x shape[1]= 13288

In [ ]:
print("ndim of DataFrame = {}\nndim of series ={}".format(df_ndim,series_ndim))

ndim of DataFrame = 2
ndim of series =1

...

5. Data Formatting and Data Normalization: Summarize the types of
variables by checking the data types
of the variables in the data set. If
variables are not in the correct data type, apply proper type
conversions.

dtypes: to check the data types of colums in a DataFrame

In [ ]:
dataTypeSeries = df.dtypes
print("Data type of Each column of DataFrame is:")

Data type of Each column of DataFrame is:

In [ ]:
print (dataTypeSeries)

name                        object
title                       object
url                         object
author                      object
publisher                   object
issued                      object
publisher_classification    object
description                 object
tags                        object
license_id                  object
license_url                 object
license_notes               object
place                       object
location                    object
country                     object
language                    object
status                      object
metadatacreated             object
generator                   object
api_endpoint                object
api_type                    object
full_metadata_download      object
dtype: object

6.  Turn categorical variables into quantitative variables in Python.

get_dummies() : this method will return dummy variable colums.

concat() : to concatenate dummy columns into DataFrames

In [ ]:
dumies = pd.get_dummies(df.author)

In [ ]:
merged = pd.concat([df,dumies], axis  = 'columns')
merged.drop(['author'],axis = 'columns')

,name,title,url,publisher,issued,publisher_classification,description,tags,license_id,license_url,...,Wyre Council,Xunta de Galicia,data.go.kr,data.gov.sk,e-Government Center,http://g0vhk.io,http://garagelab.tumblr.com/,pinardag,regione sardegna,Örebro Kommun
0,a2gov_org,"Ann Arbor, Michigan",http://www.a2gov.org/services/data/Pages/defau...,City of Ann Arbor,NaN,NaN,City of Ann Arbor's Open Data Catalog (USA),ctic unitedstates,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
1,acikveri-sahinbey-bel-tr,Açık Veri Portali - Test Yayını,http://acikveri.sahinbey.bel.tr/dataset,SahinBey Belediyesi,31/01/2015,Government,The first official open data portal of Turkey,turkey national,Unknown,NaN,...,0,0,0,0,0,0,0,1,0,0
2,africa_open_data,Africa Open Data,http://africaopendata.org/,Africa Open Data,NaN,NaN,Africa's largest central repository for Govern...,ckan africa,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
3,ajuntament-de-tarragona,Open Data Tarragona,http://opendata.tarragona.cat/,Ajuntament de Tarragona,NaN,Government,Open Data Tarragona,city spain,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4,ajuntament-de-terassa,Open Data Terassa,http://opendata.terrassa.cat/,Ajuntament de Terassa,NaN,Government,Open Data Terassa,city spain,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,open-data-nepal,Open Data Nepal,https://opendatanepal.com/,Open Knowledge Nepal,2018-03-03,Community,A civil society initiative to make Nepal’s dat...,ckan nepal,cc-by,https://creativecommons.org/licenses/by/4.0/,...,0,0,0,0,0,0,0,0,0,0
600,stat-tj,Agency on Statistics under President of the Re...,https://www.stat.tj/en,The Statistical Agency under President of the ...,NaN,Government,The information in the Statistical Agency is p...,tajikistan statistics,Other (Not Open),NaN,...,0,0,0,0,0,0,0,0,0,0
601,dadosjusbr,DadosJusBR,https://dadosjusbr.org/,Instituto Federal de Alagoas,2018-12-31,Community,The portal consumes or scrapes data from sever...,brazil judiciary,cc-by,NaN,...,0,0,0,0,0,0,0,0,0,0
602,bratislava-opendata,Bratislava Open Data Portal,https://opendata.bratislava.sk,The city of Bratislava,NaN,Government,Open data is information or data that is freel...,bratislava slovakia,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
603,sk-kosice-opendata,The city of Košice Open Data Portal,https://opendata.kosice.sk,The city of Košice,NaN,Government,The Open Data Portal is one of the outputs of ...,kosice slovakia,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
print(merged)

                         name  \
0                   a2gov_org
1    acikveri-sahinbey-bel-tr
2            africa_open_data
3     ajuntament-de-tarragona
4       ajuntament-de-terassa
..                        ...
599           open-data-nepal
600                   stat-tj
601                dadosjusbr
602       bratislava-opendata
603        sk-kosice-opendata

                                                 title  \
0                                  Ann Arbor, Michigan
1                      Açık Veri Portali - Test Yayını
2                                     Africa Open Data
3                                  Open Data Tarragona
4                                    Open Data Terassa
..                                                 ...
599                                    Open Data Nepal
600  Agency on Statistics under President of the Re...
601                                         DadosJusBR
602                        Bratislava Open Data Portal
603                The city of Košice Open Data Portal

                                                   url  \
0    http://www.a2gov.org/services/data/Pages/defau...
1              http://acikveri.sahinbey.bel.tr/dataset
2                           http://africaopendata.org/
3                       http://opendata.tarragona.cat/
4                        http://opendata.terrassa.cat/
..                                                 ...
599                         https://opendatanepal.com/
600                             https://www.stat.tj/en
601                            https://dadosjusbr.org/
602                     https://opendata.bratislava.sk
603                         https://opendata.kosice.sk

                                                author  \
0                                    City of Ann Arbor
1                                             pinardag
2                                     Africa Open Data
3                              Ajuntament de Tarragona
4                                Ajuntament de Terassa
..                                                 ...
599                               Open Knowledge Nepal
600  The Statistical Agency under President of the ...
601  Instituto Federal de Alagoas (IFAL) in partner...
602  Magistrát hlavného mesta Slovenskej republiky ...
603                             Magistrát mesta Košice

                                             publisher      issued  \
0                                    City of Ann Arbor         NaN
1                                  SahinBey Belediyesi  31/01/2015
2                                     Africa Open Data         NaN
3                              Ajuntament de Tarragona         NaN
4                                Ajuntament de Terassa         NaN
..                                                 ...         ...
599                               Open Knowledge Nepal  2018-03-03
600  The Statistical Agency under President of the ...         NaN
601                       Instituto Federal de Alagoas  2018-12-31
602                             The city of Bratislava         NaN
603                                 The city of Košice         NaN

    publisher_classification  \
0                        NaN
1                 Government
2                        NaN
3                 Government
4                 Government
..                       ...
599                Community
600               Government
601                Community
602               Government
603               Government

                                           description                   tags  \
0          City of Ann Arbor's Open Data Catalog (USA)      ctic unitedstates
1        The first official open data portal of Turkey        turkey national
2    Africa's largest central repository for Govern...            ckan africa
3                                  Open Data Tarragona             city spain
4                                    Open Data Terassa             city spain
..                                                 ...                    ...
599  A civil society initiative to make Nepal’s dat...             ckan nepal
600  The information in the Statistical Agency is p...  tajikistan statistics
601  The portal consumes or scrapes data from sever...       brazil judiciary
602  Open data is information or data that is freel...    bratislava slovakia
603  The Open Data Portal is one of the outputs of ...        kosice slovakia

           license_id  ... Wyre Council Xunta de Galicia data.go.kr  \
0                 NaN  ...            0                0          0
1             Unknown  ...            0                0          0
2                 NaN  ...            0                0          0
3                 NaN  ...            0                0          0
4                 NaN  ...            0                0          0
..                ...  ...          ...              ...        ...
599             cc-by  ...            0                0          0
600  Other (Not Open)  ...            0                0          0
601             cc-by  ...            0                0          0
602               NaN  ...            0                0          0
603               NaN  ...            0                0          0

    data.gov.sk e-Government Center http://g0vhk.io  \
0             0                   0               0
1             0                   0               0
2             0                   0               0
3             0                   0               0
4             0                   0               0
..          ...                 ...             ...
599           0                   0               0
600           0                   0               0
601           0                   0               0
602           0                   0               0
603           0                   0               0

    http://garagelab.tumblr.com/ pinardag regione sardegna Örebro Kommun
0                              0        0                0             0
1                              0        1                0             0
2                              0        0                0             0
3                              0        0                0             0
4                              0        0                0             0
..                           ...      ...              ...           ...
599                            0        0                0             0
600                            0        0                0             0
601                            0        0                0             0
602                            0        0                0             0
603                            0        0                0             0

[604 rows x 519 columns]

Experiment number 1 done. Data wrangling